insert into user_address (user_id, state, city, street, zip_code) values (75, 'New York', 'White Plains', 'Drive', '10606');
insert into user_address (user_id, state, city, street, zip_code) values (31, 'Nevada', 'Sparks', 'Circle', '89436');
insert into user_address (user_id, state, city, street, zip_code) values (414, 'California', 'Whittier', 'Way', '90610');
insert into user_address (user_id, state, city, street, zip_code) values (445, 'North Carolina', 'Raleigh', 'Hill', '27658');
insert into user_address (user_id, state, city, street, zip_code) values (497, 'Texas', 'El Paso', 'Road', '79916');
insert into user_address (user_id, state, city, street, zip_code) values (545, 'Louisiana', 'New Orleans', 'Center', '70116');
insert into user_address (user_id, state, city, street, zip_code) values (301, 'Florida', 'Orlando', 'Park', '32813');
insert into user_address (user_id, state, city, street, zip_code) values (600, 'Minnesota', 'Saint Paul', 'Hill', '55172');
insert into user_address (user_id, state, city, street, zip_code) values (110, 'New York', 'Brooklyn', 'Point', '11215');
insert into user_address (user_id, state, city, street, zip_code) values (319, 'Colorado', 'Boulder', 'Pass', '80310');
insert into user_address (user_id, state, city, street, zip_code) values (414, 'Florida', 'Miami', 'Center', '33153');
insert into user_address (user_id, state, city, street, zip_code) values (579, 'Florida', 'Tampa', 'Parkway', '33615');
insert into user_address (user_id, state, city, street, zip_code) values (283, 'Pennsylvania', 'Philadelphia', 'Street', '19184');
insert into user_address (user_id, state, city, street, zip_code) values (286, 'California', 'Simi Valley', 'Terrace', '93094');
insert into user_address (user_id, state, city, street, zip_code) values (563, 'California', 'Santa Clara', 'Street', '95054');
insert into user_address (user_id, state, city, street, zip_code) values (155, 'Colorado', 'Colorado Springs', 'Terrace', '80940');
insert into user_address (user_id, state, city, street, zip_code) values (122, 'Utah', 'Ogden', 'Street', '84409');
insert into user_address (user_id, state, city, street, zip_code) values (471, 'Texas', 'Texarkana', 'Avenue', '75507');
insert into user_address (user_id, state, city, street, zip_code) values (105, 'South Carolina', 'Greenville', 'Center', '29615');
insert into user_address (user_id, state, city, street, zip_code) values (10, 'Illinois', 'Chicago', 'Court', '60609');
insert into user_address (user_id, state, city, street, zip_code) values (138, 'Florida', 'Saint Augustine', 'Avenue', '32092');
insert into user_address (user_id, state, city, street, zip_code) values (466, 'Texas', 'Houston', 'Park', '77288');
insert into user_address (user_id, state, city, street, zip_code) values (4, 'California', 'Oakland', 'Circle', '94605');
insert into user_address (user_id, state, city, street, zip_code) values (117, 'Pennsylvania', 'Philadelphia', 'Circle', '19104');
insert into user_address (user_id, state, city, street, zip_code) values (65, 'Texas', 'El Paso', 'Plaza', '88553');
insert into user_address (user_id, state, city, street, zip_code) values (53, 'Virginia', 'Arlington', 'Lane', '22217');
insert into user_address (user_id, state, city, street, zip_code) values (199, 'Michigan', 'Ann Arbor', 'Plaza', '48107');
insert into user_address (user_id, state, city, street, zip_code) values (506, 'Tennessee', 'Memphis', 'Junction', '38197');
insert into user_address (user_id, state, city, street, zip_code) values (262, 'California', 'Anaheim', 'Hill', '92805');
insert into user_address (user_id, state, city, street, zip_code) values (186, 'Georgia', 'Savannah', 'Pass', '31410');
insert into user_address (user_id, state, city, street, zip_code) values (199, 'South Carolina', 'Columbia', 'Street', '29208');
insert into user_address (user_id, state, city, street, zip_code) values (331, 'California', 'Los Angeles', 'Plaza', '90035');
insert into user_address (user_id, state, city, street, zip_code) values (343, 'Florida', 'Sarasota', 'Circle', '34276');
insert into user_address (user_id, state, city, street, zip_code) values (404, 'Texas', 'El Paso', 'Hill', '79999');
insert into user_address (user_id, state, city, street, zip_code) values (473, 'New Jersey', 'Trenton', 'Court', '08619');
insert into user_address (user_id, state, city, street, zip_code) values (53, 'Idaho', 'Idaho Falls', 'Avenue', '83405');
insert into user_address (user_id, state, city, street, zip_code) values (409, 'New York', 'New York City', 'Place', '10029');
insert into user_address (user_id, state, city, street, zip_code) values (47, 'Pennsylvania', 'Philadelphia', 'Junction', '19196');
insert into user_address (user_id, state, city, street, zip_code) values (462, 'Florida', 'West Palm Beach', 'Pass', '33405');
insert into user_address (user_id, state, city, street, zip_code) values (516, 'Tennessee', 'Memphis', 'Road', '38114');
insert into user_address (user_id, state, city, street, zip_code) values (308, 'Nebraska', 'Lincoln', 'Road', '68524');
insert into user_address (user_id, state, city, street, zip_code) values (202, 'Pennsylvania', 'Pittsburgh', 'Lane', '15235');
insert into user_address (user_id, state, city, street, zip_code) values (126, 'Texas', 'El Paso', 'Drive', '79905');
insert into user_address (user_id, state, city, street, zip_code) values (257, 'Georgia', 'Atlanta', 'Place', '30316');
insert into user_address (user_id, state, city, street, zip_code) values (356, 'California', 'Bakersfield', 'Crossing', '93305');
insert into user_address (user_id, state, city, street, zip_code) values (285, 'California', 'Chico', 'Circle', '95973');
insert into user_address (user_id, state, city, street, zip_code) values (392, 'Texas', 'El Paso', 'Plaza', '88530');
insert into user_address (user_id, state, city, street, zip_code) values (169, 'New York', 'Buffalo', 'Parkway', '14233');
insert into user_address (user_id, state, city, street, zip_code) values (323, 'Florida', 'Fort Myers', 'Park', '33994');
insert into user_address (user_id, state, city, street, zip_code) values (506, 'District of Columbia', 'Washington', 'Street', '20580');
